name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        uses: pypush/install-theos@v1
      - name: Build Package
        run: make package FINALPACKAGE=1
